FROM node:14.21.2

ARG PORT

ENV CLOUD_STORAGE_PROJECT_NAME=$CLOUD_STORAGE_PROJECT_NAME
ENV CLOUD_STORAGE_BUCKET=$CLOUD_STORAGE_BUCKET
ENV SECRET_KEY=$SECRET_KEY
ENV PORT=$PORT

WORKDIR /app
COPY package*.json ./
# COPY package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE ${PORT}

CMD ["npm","start"]